baseURL = "https://hbowley.github.io/Portfolio/"
languageCode = "en-us"
title = "Hannah Bowley"
theme = "minimal"

[params]
description = "Data scientist, biostatistician, and analytics consultant based in Miami"
author = "Hannah Bowley"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 2

[[menu.main]]
name = "Projects"
pageRef = "/projects"
weight = 3

[[menu.main]]
name = "Publications"
pageRef = "/publications"
weight = 4

[[menu.main]]
name = "Resume"
pageRef = "/resume"
weight = 5

[[menu.main]]
name = "Contact"
pageRef = "/contact"
weight = 6

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
